// Sample translations (expand to 500 in actual implementation)
const translations = [
    { language: "English", phrase: "I love you" },
    { language: "Spanish", phrase: "Te amo" },
    { language: "French", phrase: "Je t'aime" },
    { language: "German", phrase: "Ich liebe dich" },
    { language: "Italian", phrase: "Ti amo" },
    { language: "Portuguese", phrase: "Eu te amo" },
    { language: "Dutch", phrase: "Ik hou van jou" },
    { language: "Russian", phrase: "Я тебя люблю" },
    { language: "Japanese", phrase: "愛してる" },
    { language: "Chinese (Mandarin)", phrase: "我爱你" },
    { language: "Korean", phrase: "사랑해" },
    { language: "Arabic", phrase: "أحبك" },
    { language: "Hindi", phrase: "मैं तुमसे प्यार करता हूँ" },
    { language: "Bengali", phrase: "আমি তোমায় ভালোবাসি" },
    { language: "Urdu", phrase: "میں تم سے پیار کرتا ہوں" },
    { language: "Turkish", phrase: "Seni seviyorum" },
    { language: "Vietnamese", phrase: "Anh yêu em" },
    { language: "Thai", phrase: "ฉันรักคุณ" },
    { language: "Polish", phrase: "Kocham cię" },
    { language: "Ukrainian", phrase: "Я тебе кохаю" },
    { language: "Swedish", phrase: "Jag älskar dig" },
    { language: "Greek", phrase: "Σ' αγαπώ" },
    { language: "Czech", phrase: "Miluji tě" },
    { language: "Danish", phrase: "Jeg elsker dig" },
    { language: "Finnish", phrase: "Minä rakastan sinua" },
    { language: "Norwegian", phrase: "Jeg elsker deg" },
    { language: "Hungarian", phrase: "Szeretlek" },
    { language: "Romanian", phrase: "Te iubesc" },
    { language: "Hebrew", phrase: "אני אוהב אותך" },
    { language: "Indonesian", phrase: "Aku cinta kamu" },
    { language: "Malay", phrase: "Saya cintakan awak" },
    { language: "Filipino", phrase: "Mahal kita" },
    { language: "Swahili", phrase: "Nakupenda" },
    { language: "Persian", phrase: "دوستت دارم" },
    { language: "Bulgarian", phrase: "Обичам те" },
    { language: "Slovak", phrase: "Ľúbim ťa" },
    { language: "Croatian", phrase: "Volim te" },
    { language: "Serbian", phrase: "Волим те" },
    { language: "Lithuanian", phrase: "Aš tave myliu" },
    { language: "Latvian", phrase: "Es tevi mīlu" },
    { language: "Estonian", phrase: "Ma armastan sind" },
    { language: "Slovenian", phrase: "Ljubim te" },
    { language: "Macedonian", phrase: "Те сакам" },
    { language: "Albanian", phrase: "Të dua" },
    { language: "Bosnian", phrase: "Volim te" },
    { language: "Icelandic", phrase: "Ég elska þig" },
    { language: "Irish", phrase: "Tá grá agam duit" },
    { language: "Welsh", phrase: "Rwy'n dy garu di" },
    { language: "Scottish Gaelic", phrase: "Tha gaol agam ort" },
    { language: "Basque", phrase: "Maite zaitut" },
    { language: "Catalan", phrase: "T'estimo" },
    { language: "Galician", phrase: "Quérote" },
    { language: "Luxembourgish", phrase: "Ech hunn dech gär" },
    { language: "Maltese", phrase: "Inħobbok" },
    { language: "Afrikaans", phrase: "Ek het jou lief" },
    { language: "Zulu", phrase: "Ngiyakuthanda" },
    { language: "Xhosa", phrase: "Ndiyakuthanda" },
    { language: "Shona", phrase: "Ndinokuda" },
    { language: "Yoruba", phrase: "Mo nifẹ rẹ" },
    { language: "Igbo", phrase: "A huru m gi n'anya" },
    { language: "Hausa", phrase: "Ina son ka" },
    { language: "Amharic", phrase: "እወድሃለሁ" },
    { language: "Somali", phrase: "Waan ku jeclahay" },
    { language: "Oromo", phrase: "Sin jaladha" },
    { language: "Tigrinya", phrase: "ይፈትወካ" },
    { language: "Kirundi", phrase: "Ndagukunda" },
    { language: "Kinyarwanda", phrase: "Ndagukunda" },
    { language: "Sesotho", phrase: "Kea u rata" },
    { language: "Tswana", phrase: "Ke a go rata" },
    { language: "Tsonga", phrase: "Ndza ku rhandza" },
    { language: "Venda", phrase: "Ndi a ni funa" },
    { language: "Ndebele", phrase: "Ngiyakuthanda" },
    { language: "Malagasy", phrase: "Tiako ianao" },
    { language: "Mauritian Creole", phrase: "Mo kontan twa" },
    { language: "Seychellois Creole", phrase: "Mon kontan ou" },
    { language: "Comorian", phrase: "Nakupenda" },
    { language: "Dhivehi", phrase: "އަހަރެން ތިބާ ދެކެވުން" },
    { language: "Sinhala", phrase: "මම ඔයාට ආදරෙයි" },
    { language: "Nepali", phrase: "म तिमीलाई माया गर्छु" },
    { language: "Tibetan", phrase: "ང་ཁྱེད་ལ་དགའ" },
    { language: "Dzongkha", phrase: "ང་ཁྱོད་ལ་དགའ" },
    { language: "Burmese", phrase: "ချစ်တယ်" },
    { language: "Khmer", phrase: "ខ្ញុំស្រឡាញ់អ្នក" },
    { language: "Lao", phrase: "ຂ້ອຍຮັກເຈົ້າ" },
    { language: "Mongolian", phrase: "Би чамд хайртай" },
    { language: "Uighur", phrase: "مەن سىزنى ياخشى كۆرىمەن" },
    { language: "Kazakh", phrase: "Мен сені жақсы көремін" },
    { language: "Kyrgyz", phrase: "Мен сени сүйөм" },
    { language: "Tajik", phrase: "Ман туро дӯст медорам" },
    { language: "Turkmen", phrase: "Men seni söýýärin" },
    { language: "Uzbek", phrase: "Men seni sevaman" },
    { language: "Armenian", phrase: "Ես քեզ սիրում եմ" },
    { language: "Georgian", phrase: "მიყვარხარ" },
    { language: "Azerbaijani", phrase: "Mən səni sevirəm" },
    { language: "Chechen", phrase: "Со хьо векха везар" },
    { language: "Ossetian", phrase: "Аз дæ уарзын" },
    { language: "Abkhaz", phrase: "Сара бараны бзиа бзиабара" },
    { language: "Avar", phrase: "Нух малъараб лъикІарав" },
    { language: "Lezgian", phrase: "Заз хъф лугьузва" },
    { language: "Kumyk", phrase: "Мен сени севем" },
    { language: "Nogai", phrase: "Мен сені сүйемін" },
    { language: "Karachay-Balkar", phrase: "Мен сени сюем" },
    { language: "Adyghe", phrase: "Сэ уэзыфэшъу" },
    { language: "Kabardian", phrase: "Сэ уэзышIу" },
    { language: "Cherokee", phrase: "ᎬᏍᏓᏆ" },
    { language: "Navajo", phrase: "Ayóó ánííníshní" },
    { language: "Inuktitut", phrase: "ᖁᕕᐊᓱᒋᑦᓯ" },
    { language: "Cree", phrase: "ᑭᓇᓈᐦᑯᒥᑖᐤ" },
    { language: "Ojibwe", phrase: "Gi-zaagi'in" },
    { language: "Lakota", phrase: "Techihhila" },
    { language: "Hawaiian", phrase: "Aloha wau iā ʻoe" },
    { language: "Samoan", phrase: "Ou te alofa ia te oe" },
    { language: "Tongan", phrase: "Ofa atu" },
    { language: "Maori", phrase: "Aroha ahau ki a koe" },
    { language: "Fijian", phrase: "Au domoni iko" },
    { language: "Tahitian", phrase: "Ua here au ia oe" },
    { language: "Chamorro", phrase: "Hu guaiya hao" },
    { language: "Marshallese", phrase: "Ij iakwe eok" },
    { language: "Palauan", phrase: "Ak morolung" },
    { language: "Yapese", phrase: "Tamag" },
    { language: "Kosraean", phrase: "Ngoh sramsram ohng" },
    { language: "Pohnpeian", phrase: "I kohsuisih" },
    { language: "Chuukese", phrase: "Au pwan ren" },
    { language: "Nauruan", phrase: "Eko dogin" },
    { language: "Kiribati", phrase: "I tangiriko" },
    { language: "Tuvaluan", phrase: "Au alofa ia te oe" },
    { language: "Tok Pisin", phrase: "Mi laikim yu" },
    { language: "Bislama", phrase: "Mi lavem yu" },
    { language: "Hiri Motu", phrase: "Lau ese oi hereva" },
    { language: "Guaraní", phrase: "Rojhayhû" },
    { language: "Quechua", phrase: "Kuyayki" },
    { language: "Aymara", phrase: "Munayki" },
    { language: "Mapudungun", phrase: "Inche ta mun" },
    { language: "Wayuu", phrase: "Aishi'püshi" },
    { language: "Nahuatl", phrase: "Ni mitz tlazohtla" },
    { language: "Mixtec", phrase: "Nakuíí" },
    { language: "Zapotec", phrase: "Xtyozën" },
    { language: "Maya", phrase: "In k'aatech" },
    { language: "Tzotzil", phrase: "Te quiero" },
    { language: "K'iche'", phrase: "Kikotem" },
    { language: "Kaqchikel", phrase: "Xtikowisaj" },
    { language: "Q'eqchi'", phrase: "Tajin kti'oj" },
    { language: "Mam", phrase: "Tajin kti'oj" },
    { language: "Garifuna", phrase: "Lidawli" },
    { language: "Miskito", phrase: "Naksa" }
];


const quotes = [
    "You’re the melody to my heart’s song. 🎶",
    "In your eyes, I found my forever home. 🏡",
    "Every moment with you feels like a dream. 💭",
    "You’re the reason my soul dances in the moonlight. 🌙",
    "My love for you grows with every heartbeat. 💓",
    "You’re the spark that lights up my days. ✨",
    "With you, every day is a love story. 📖",
    "You’re my safe haven in a wild world. 🛖",
    "I’d cross oceans just to see you smile. 🌊",
    "Your love is the sweetest gift I’ve ever known. 🎁",
    "You’re the missing piece I didn’t know I needed. 🧩",
    "My heart whispers your name every second. 💬",
    "You’re the sunshine breaking through my clouds. ☀️",
    "Loving you is as easy as breathing. 🌬️",
    "You’re the star guiding me through the night. ⭐",
    "In a chaotic world, you are my calm. 🕊️",
    "Your smile is my favorite kind of magic. 🪄",
    "I fell for you, and I’m still falling. 🍂",
    "You’re the reason I believe in fairy tales. 🧚",
    "My heart chose you forever. 💞",
    "You’re the warmth in my coldest days. 🔥",
    "Every love song reminds me of you. 🎵",
    "You’re my forever and always. ⏳",
    "With you, time feels infinite. ∞",
    "Your laughter is my favorite tune. 😂",
    "I’d pick you in every lifetime. 🌍",
    "You’re the color in my gray world. 🌈",
    "My heart beats only for you. 💗",
    "You’re the dream I never want to end. 😴",
    "Loving you is my greatest adventure. 🗺️",
    "You’re the reason I smile for no reason. 😊",
    "In your arms, I’ve found paradise. 🌴",
    "You’re my everything and more. 🌟",
    "Your love paints my life with joy. 🎨",
    "I’m yours, now and always. 🔒",
    "You’re the rhythm to my soul’s dance. 💃",
    "Every glance from you takes my breath away. 😮",
    "You’re the love I’ll always fight for. ⚔️",
    "With you, I’ve found my true self. 🪞",
    "You’re the light that guides me home. 🏠",
    "My love for you has no limits. 🚀",
    "You’re the reason my heart sings. 🎤",
    "In your presence, I feel unstoppable. 💪",
    "You’re my sweetest hello and toughest goodbye. 👋",
    "Your love anchors me in every storm. ⚓",
    "I’d choose you over a thousand sunsets. 🌅",
    "You’re the poetry my heart writes. ✍️",
    "With you, every moment is precious. ⏰",
    "You’re the flame that keeps me warm. 🕯️",
    "My love for you is deeper than the sea. 🌊",
    "You’re the wish I didn’t know I made. 🌠",
    "In your arms, I’ve found forever. 🤗",
    "You’re the reason I believe in fate. 🔮",
    "Your voice is my favorite lullaby. 🎼",
    "I’m lost in you, and I love it. 🌀",
    "You’re the heartbeat of my every day. 💓",
    "With you, love feels magical. 🪄",
    "You’re the smile behind my every laugh. 😄",
    "My heart belongs to you alone. 💝",
    "You’re the dawn that brightens my mornings. 🌞",
    "Loving you is my favorite pastime. 🕒",
    "You’re the love I’ll never let go. 🤝",
    "In your eyes, I see my tomorrow. 👀",
    "You’re the reason my world shines. 🌍",
    "Your touch is my sweetest comfort. 🖐️",
    "I’d travel the stars to be with you. 🌌",
    "You’re the love that fills my thoughts. 💭",
    "With you, I’ve found my happy ending. 🏰",
    "You’re the beat that keeps me alive. 🎧",
    "My love for you is endless. ♾️",
    "You’re the reason I believe in miracles. 🙏",
    "In your smile, I find my happiness. 😊",
    "You’re my one and only. 🥇",
    "With you, every day is a blessing. 🌸",
    "You’re the love I’ll cherish forever. 💎",
    "Your kiss is my sweetest escape. 💋",
    "You’re the reason my heart races. 🏃",
    "In your love, I’ve found my strength. 💪",
    "You’re my sunshine on stormy days. ⛈️",
    "With you, I feel complete. 🧩",
    "You’re the spark in my every moment. ⚡",
    "My heart calls your name every night. 🌜",
    "You’re the rose in my garden of life. 🌹",
    "Loving you feels like flying. 🕊️",
    "You’re the treasure I’ll always seek. 🗝️",
    "In your embrace, I’m home. 🏡",
    "You’re the reason I wake up smiling. 🌞",
    "Your love is my greatest victory. 🏆",
    "You’re the star in my sky. ✨",
    "With you, every second is perfect. ⏳",
    "You’re the love that lights my way. 🏮",
    "My heart dances when you’re near. 💃",
    "You’re the reason I believe in love. 💘",
    "In your presence, I’m whole. 🧡",
    "You’re my sweetest dream come true. 🌙",
    "Your love is my guiding compass. 🧭",
    "You’re the joy in my every day. 🎉",
    "With you, life is a beautiful journey. 🛤️",
    "You’re the flame in my heart. 🔥",
    "My love for you grows stronger daily. 🌱",
    "You’re the reason I feel alive. 🌟",
    "In your smile, I see my world. 😊",
    "You’re my forever companion. 👫",
    "Your touch ignites my soul. 🔥",
    "You’re the love I’ll always hold. 🤲",
    "With you, every night is starry. 🌠",
    "You’re the heartbeat of my life. 💓",
    "My love for you is unbreakable. 💪",
    "You’re the reason I dream in color. 🌈",
    "In your arms, I’ve found peace. 🕊️",
    "You’re my sweetest addiction. 🍫",
    "Your love is my endless horizon. 🌅",
    "You’re the magic in my ordinary days. ✨",
    "With you, I’m never lost. 🗺️",
    "You’re the love that keeps me going. 🚀",
    "My heart sings your praises. 🎶",
    "You’re the reason my days are bright. ☀️",
    "In your eyes, I see eternity. 👁️",
    "You’re my favorite hello. 👋",
    "Your love is my warmest blanket. 🛌",
    "You’re the star of my love story. ⭐",
    "With you, every moment sparkles. 💖",
    "You’re the rhythm of my life. 🎵",
    "My love for you is timeless. ⏰",
    "You’re the reason I believe in us. 💑",
    "In your laughter, I find joy. 😂",
    "You’re my sweetest serenity. 🌿",
    "Your love lifts me higher. 🎈",
    "You’re the light in my darkest nights. 🌜",
    "With you, I’ve found my soulmate. 💞",
    "You’re the beat of my every song. 🎤",
    "My heart is yours forevermore. 💝",
    "You’re the reason love feels real. 💗",
    "In your embrace, I’m infinite. ♾️",
    "You’re my sunshine and my rain. 🌦️",
    "Your love is my greatest treasure. 💰",
    "You’re the spark that starts my day. ⚡",
    "With you, every kiss is magic. 💋",
    "You’re the love I’ll never tire of. 💕",
    "My heart belongs to you eternally. 💍"
];

// DOM Elements
const translationEl = document.getElementById("translation");
const languageEl = document.getElementById("language");
const nextBtn = document.getElementById("next");
const quoteBox = document.getElementById("quoteBox");
const background = document.getElementById("background");
let currentIndex = 0;

// Update displayed translation and language
function updateTranslation() 
{
    const { phrase, language } = translations[currentIndex];
    translationEl.textContent = phrase;
    languageEl.textContent = language;

    // Update quote
    const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
    quoteBox.textContent = randomQuote;
}

// Handle next translation with fade animation
function nextTranslation() 
{
    translationEl.style.opacity = 0;
    languageEl.style.opacity = 0;
    quoteBox.style.opacity = 0;
    setTimeout(() => {
    currentIndex = (currentIndex + 1) % translations.length;
    updateTranslation();
    translationEl.style.opacity = 1;
    languageEl.style.opacity = 1;
    quoteBox.style.opacity = 1;
    }, 500);
}

// Event listener for button
nextBtn.addEventListener('click', nextTranslation);

// Initialize with first translation
updateTranslation();

// Create floating hearts
const colors = ['#ff69b4', '#ff1493', '#db7093', '#ffc0cb'];
for (let i = 0; i < 30; i++) 
{
    const heart = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    heart.setAttribute("class", "heart");
    heart.setAttribute("width", "20");
    heart.setAttribute("height", "20");
    const use = document.createElementNS("http://www.w3.org/2000/svg", "use");
    use.setAttribute("href", "#heart");
    heart.appendChild(use);
    heart.style.left = `${Math.random() * 100}vw`;
    heart.style.animationDuration = `${5 + Math.random() * 10}s`;
    heart.style.animationDelay = `${Math.random() * 5}s`;
    heart.style.fill = colors[Math.floor(Math.random() * colors.length)];
    background.appendChild(heart);
}